### PR TITLE
FE- Forum-Posts-#80

### PR DESCRIPTION
**Pull request by jonquag**
Added a post modal to open off each Post Card

### CODE REVIEW

**Comment by jonquag** [comment]
post modal

**Comment by jonquag** [comment]
I've also adjusted the modal window to use the screen width to calculate its size and gutters.

I'm thinking about moving the upvote button to a new location as the placement may be confused for upvoting the comment. 
For the description portion, I was also thinking about using more gutter space and throwing the upvote icon in there.
Please let me know your thoughts.

**Comment by jonquag** [comment]
Here are some updated responsiveness looks

Desktop:

desktop post dialog

Tablet: 

ipad post dialog

Mobile:

iphone post dialog

**Review by jessdesr — APPROVED** [review]
This one also looks good, just clean up the various comments, resolve merge conflicts and whatnot and you can continue work on integration from there!

**Pull request merged**
