### PR TITLE
Fe redirects 59

### PR DESCRIPTION
**Pull request by timegambit**
Screen Shot 2021-01-27 at 7 34 57 PM

Preview of the 404 not found page.

I was having issues with the NavBar always showing up on the 404 page because the Layout component always at least renders the NavBar. To fix that I moved the NavBar from the layout to the ProtectedRoutes.  It should work because all routes inside our app are protected (and therefore will get the NavBar), but if anyone has a different solution let me know!

### CODE REVIEW

**Review by amha19 — APPROVED** [review]
It seems to work fine. 
Suggestion: For a logged in user if they somehow end up at a not found page, a button or a link back to the profile or login page will be helpful. But this might be a personal preference.

**Comment by ethanrosenberg** [comment]
works great for me. Amha has a point might be nice to have a link for the user to click! Nice job Ethan!

**Comment by jonquag** [comment]
> It seems to work fine.
> Suggestion: For a logged in user if they somehow end up at a not found page, a button or a link back to the profile or login page will be helpful. But this might be a personal preference.

This is a great idea.

**Review by jonquag — APPROVED** [review]

**Comment by timegambit** [comment]
> It seems to work fine.
> Suggestion: For a logged in user if they somehow end up at a not found page, a button or a link back to the profile or login page will be helpful. But this might be a personal preference.

Good idea, I added a Login link that always shows and a profile link that shows if the user is authenticated.

**Pull request merged**
