### PR TITLE
In logout 47

### PR DESCRIPTION
**Pull request by timegambit**

### CODE REVIEW

**Comment by jonquag** [comment]
This seems to all be working fine but we are not requested for approval @timegambit

**Comment by timegambit** [comment]
> This seems to all be working fine but we are not requested for approval @timegambit

Sorry about that!

**Comment by jessdesr** [comment]
> This seems to all be working fine but we are not requested for approval @timegambit

Usually, even if you're not request for approval, you should still be able to do so.  Permissions in this repo might be different though.

**Review by jessdesr — COMMENTED** [review]
This one's got a few of the changes you made in the error PR, so I'll come back to this once that's merged

**Review by amha19 — APPROVED** [review]
It is working properly. Deletes the token from Cookies.

**Review by ethanrosenberg — APPROVED** [review]
works fine for me and clears cookies properly!

**Review by jonquag — APPROVED** [review]
Looks in working order

**Pull request merged**
