### PR TITLE
Demo branch

### PR DESCRIPTION
**Pull request by amha19**
Fixed fetching and storing user info after demo merge.

### CODE REVIEW

**Comment by timegambit** [comment]
@amha19 because this is just a big PR, I'm thinking we should get all of our branches merged into dev that are contained in this PR first, and then merge dev into this branch to see any changes from there? What are your thoughts?

**Comment by amha19** [comment]
@timegambit That sounds logical. The good thing is, we will have cleaner branches and merges and the minor drawback would be to do conflict resolving again.

**Comment by jonquag** [comment]
I just quickly added the placeholders for the inputs to this branch.

Should we get together and do another merge resolve before (or even after) sprint planning today?

**Comment by ethanrosenberg** [comment]
Sounds like a good idea to me. Can only help!

**Comment by amha19** [comment]
Any remaining changes in the demo branch that haven't been merged to the dev branch will be made as a new pull request.

**Pull request closed without merging**
